Correction-matrix-StandingWave
Xiangyu-Hu/SPHinXsys pull request #190
Opened 2023-01-13 10:07 UTC by SPHYaru

1. add the weighted kernel gradient correction.
2. add the standing wave case.

2023-01-19 13:15 UTC, Xiangyu-Hu commented
> 1. add the weighted kernel gradient correction.
> 2. add the standing wave case.

Hi, according to the file changed. It seems quite some changes in the library. Could you move these file to the folder of the test?

2023-02-15 17:21 UTC, Xiangyu-Hu commented
I seems that CI has not pass. Could you recompile it with update master branch?

2023-03-11 11:43 UTC, ChiZhangatTUM commented
Why un-used variable is reported as error?

2023-03-12 15:40 UTC, DongWuTUM approved these changes

2023-03-12 16:04 UTC, Xiangyu-Hu requested changes

2023-03-12 16:04 UTC, Xiangyu-Hu commented on tests/2d_examples/test_2d_standing_wave/fluid_dynamics_complex_correct.hpp
> +			BaseIntegration1stHalfCorrectType::interaction(index_i, dt);
This is the same as before. Do we really need a new class?

2023-03-12 16:04 UTC, Xiangyu-Hu commented on tests/2d_examples/test_2d_standing_wave/fluid_dynamics_inner_correct.hpp
> +			vel_[index_i] += (acc_prior_[index_i] + acc_[index_i]) * dt;
This also the same as the one in the library. Do wee need a repeated new class?

2023-03-12 16:04 UTC, Xiangyu-Hu commented on tests/2d_examples/test_2d_standing_wave/fluid_dynamics_inner_correct.hpp
> +			vel_[index_i] += (acc_prior_[index_i] + acc_[index_i]) * dt;
The code quality seems should be improved.

2023-05-10 17:38 UTC, closed without merging