add test_2d_dambreak_python case with pybind
Xiangyu-Hu/SPHinXsys pull request #225
Opened 2023-03-23 13:58 UTC by maiyetum95

2023-03-23 21:23 UTC, Xiangyu-Hu commented
> _ No description provided. _

Please provide a description to the changes.

2023-03-23 22:24 UTC, maiyetum95 commented on tests/2d_examples/test_2d_dambreak_python/pybind_tool/pybind_test.py
Add the path of the generated files from cpp (shared object in LInux and dynamic link libraries in Windows) to the python script, which should be corresponds to the folder where the file is generated.

2023-03-23 22:33 UTC, maiyetum95 commented on tests/2d_examples/test_2d_dambreak_python/CMakeLists.txt
If there are several python version in the computer, make sure that the python version here running the python script should be the same with the version which generated dynamic files.

2023-03-23 22:38 UTC, maiyetum95 commented on .github/workflows/ci.yml
Considering that the pybind is used as a submodule, we should initialize and update the submodule.

2023-03-23 22:44 UTC, maiyetum95 commented on CMakeLists.txt
In the main CMakeLists.txt, we add Position Independent Code (PIC) for Linux compile. 
Pybind only have head files, so we use add_subdirectory to add the module.

2023-03-23 22:47 UTC, maiyetum95 commented on SPHINXsys/src/for_2D_build/geometries/level_set_supplementary.cpp
Fix the problem when use Linux to compile the shared objects.

2023-03-23 22:56 UTC, maiyetum95 commented on tests/2d_examples/test_2d_dambreak_python/pybind_tool/pybind_tool.py
use python to run the 2d dambreak case, there are two arguments can be changed. The first is for setting restart step, the second is the total running time for the case.

2023-03-23 22:59 UTC, maiyetum95 commented on .github/workflows/ci.yml
This pybind11_dir is not necessary if use add subdirectory in cmakelists

2023-03-23 23:05 UTC, maiyetum95 commented on tests/2d_examples/test_2d_dambreak_python/dambreak_python.cpp
didn't change the main part when compared with the original dambreak case, only add cmakeTest() function for ctest when call the pybind_test.py

2023-03-27 18:18 UTC, Xiangyu-Hu commented
Its test finished in 0.11 second? It is strange.

2023-03-30 12:20 UTC, FabienPean-Virtonomy requested changes
Please write a description and reasons to the PR by editing your main comment in the conversation.

2023-03-30 12:20 UTC, FabienPean-Virtonomy commented on tests/2d_examples/test_2d_dambreak_python/CMakeLists.txt
> +    set(PYTHON_EXECUTABLE "C:/hostedtoolcache/windows/Python/3.9.13/x64/python3.exe")
This is set automatically when the Python dependency is correctly in the CMake files, with `find_package(Python ...)`, see https://cmake.org/cmake/help/latest/module/FindPython.html

2023-04-20 13:34 UTC, closed without merging