2d_diffusion_test_with_NeumannBC
Xiangyu-Hu/SPHinXsys pull request #255
Opened 2023-05-07 14:05 UTC by ChenxiZhaoTUM

This is the first case to implement multiple boundary conditions.

2023-05-08 13:41 UTC, Bo-Zhang1995 approved these changes

2023-05-08 18:40 UTC, Xiangyu-Hu commented
@ChenxiZhaoTUM  building is failed.

2023-05-08 20:01 UTC, Xiangyu-Hu requested changes

2023-05-08 20:07 UTC, Xiangyu-Hu commented on tests/user_examples/ExtraSources/extra_sources_share/diffusion_reaction_particles_with_boundary.h
> +/**
These particles definitions should be deleted.

2023-05-10 17:28 UTC, Xiangyu-Hu commented
@ChenxiZhaoTUM You need compile and run Ctest locally first and, after all tests passed, then initialize a CI test on Github by commit your changes. Otherwise github will waste the computation time for unsuccessful compiling and testing.

2023-05-13 18:26 UTC, ChenxiZhaoTUM commented
> @ChenxiZhaoTUM You need compile and run Ctest locally first and, after all tests passed, then initialize a CI test on Github by commit your changes. Otherwise github will waste the computation time for unsuccessful compiling and testing.

sorry about that, I thought I had closed this pull request. Now the local ctest has been passed, and I am retesting it by CI.

2023-05-15 05:13 UTC, Xiangyu-Hu commented
@ChenxiZhaoTUM you need merge master to your branch first, as the master has changed the directory structure.
There should be should be no conflict for it.

2023-05-15 18:59 UTC, merged