Exclusive shape yyc
Xiangyu-Hu/SPHinXsys pull request #343
Opened 2023-06-17 15:41 UTC by yyc84

exclusive shape template

2023-06-17 22:04 UTC, Xiangyu-Hu requested changes

2023-06-17 22:04 UTC, Xiangyu-Hu commented on src/shared/geometries/exclusive_shape.h
> +            Shape *base_shape_;
you do not need these?

2023-06-17 22:04 UTC, Xiangyu-Hu commented on src/shared/geometries/exclusive_shape.h
> +            return !is_inside;
simply use:
return !BaseShapeType::checkContain(probe_point);

2023-06-17 22:04 UTC, Xiangyu-Hu commented on src/shared/geometries/exclusive_shape.h
> +        };
you do not need this.

2023-06-18 08:58 UTC, ChiZhangatTUM commented on src/shared/geometries/exclusive_shape.h
> + * @brief A template shape which has the fluid outside of the geometry.
If I understood this correctly, this should be kind of masking scheme with level-set method. Can we name it MaskingGeometry or MaskingSahpe?

2023-06-18 21:36 UTC, yyc84 commented on src/shared/geometries/exclusive_shape.h
> +            return !is_inside;
ok

2023-06-18 21:37 UTC, yyc84 commented on src/shared/geometries/exclusive_shape.h
> +        };
ok

2023-06-18 21:38 UTC, yyc84 commented on src/shared/geometries/exclusive_shape.h
> + * @brief A template shape which has the fluid outside of the geometry.
region outside shape seems better

2023-06-18 21:40 UTC, yyc84 commented on src/shared/geometries/exclusive_shape.h
> + * @brief A template shape which has the fluid outside of the geometry.
it is not only for level-set, it give a negative distance value of orginal shape

2023-06-19 06:47 UTC, ChiZhangatTUM commented on src/shared/geometries/exclusive_shape.h
> + * @brief A template shape which has the fluid outside of the geometry.
The name should clearly presents the purpose of this specific region. For example ExclusiveShape indicating that the shape is excluded, while not clearly indicates for which purpose is excluded.

2023-06-19 08:13 UTC, Xiangyu-Hu commented on src/shared/geometries/exclusive_shape.h
> + * @brief A template shape which has the fluid outside of the geometry.
Probably using InverseShape?

2023-06-19 11:54 UTC, ChiZhangatTUM commented on src/shared/geometries/exclusive_shape.h
> + * @brief A template shape which has the fluid outside of the geometry.
> Probably using InverseShape?

This one is better than ExclusiveShape

2023-06-19 14:46 UTC, yyc84 commented
I passed windows on my own computer, and the case "3d_stfb" has no problem on windows computer

2023-06-20 04:53 UTC, Xiangyu-Hu approved these changes

2023-06-20 04:54 UTC, merged